# Generated by Django 4.2.6 on 2023-10-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(default='Иван Иванов', max_length=256)),
                ('phone', models.CharField(default='79999999999', max_length=20)),
                ('validate_number', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
