# Generated by Django 4.2.6 on 2023-10-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_author_age_author_profession_author_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='79999999999', max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='amount_reception',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
